name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Bước này giúp chạy Gradle nhanh hơn nhờ cache thư viện
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # - name: Build with Gradle
    #   run: ./gradlew build -x test # Tạm thời skip test nếu bạn chưa viết test case
    - name: Build with Gradle
      # Thêm lệnh cấp quyền chạy cho file gradlew trước khi thực thi
      run: |
        echo "Current path:"
        pwd
        echo "List files:"
        ls -la
        echo "List files in backend folder:"
        ls -la candidate-backend || echo "Folder candidate-backend not found!"

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/employee-be:latest .